version: "3"

services:
  thn-api:
    image: ghcr.io/xuqingfeng/thn-api:latest
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thn-api.rule=Path(`/graphql`)"
  thn-web:
    image: ghcr.io/xuqingfeng/thn-web:latest
    depends_on:
      - thn-api
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thn-web.rule=PathPrefix(`/`)"

networks:
  traefik:
    name: traefik_default
    external: true
